---
- hosts: all
  become: true
  tasks:
    - name: Install mysql-server service
      app: name=mysql-server state=present update_cache=yes

    - name: ensure mysql started
      service: name=mysql stated=started enabled=yes