---
- hosts: all
  become: true
  tasks:
    - name: Install web applications
      apt: name={{item}} state=present update_cache = yes
      with_item:
        - apache2 
        - libapache2-mod-wsgi
        - python-pip
        - python-virtualenv

    - name: ensure apache started
      service: name=apache stated=started enabled=yes

    - name: ensure mod_wsgi enabled
      apache2_module: stated=started name=wsgi
      notify: restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted