---
# tasks file for apache2
tasks:
  - name: install web applications
    apt: name={{item}} state=present
    with_item:
      - apache2 
      - libapache2-mod-wsgi
    tags: [ 'packages' ]

  - name: ensure mod_wsgi enabled
    apache2_module: stated=started name=wsgi
    notify: restart apache2
    tags: [ 'system' ]

  - name: de-activate default apache site
    file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
    notify: restart apache2
    tags: [ 'system' ]

  - name: ensure apache started
    service: name=apache stated=started enabled=yes
    tags: [ 'service' ]
